development:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: m111111
test:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: m111111
production:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: m111111


